theme: jekyll-theme-minimal

title: C. Claus #| Basic BIM 
description: Portfolio of a Python & IFC enthusiast.

#logo: https://github.com/C-Claus/Basic-BIM-Checker-for-Autodesk-Revit/blob/master/basic_bim_icons_dpi90/filter_level.png
#show_downloads: "true"

