theme: jekyll-theme-slate

title: Basic BIM tooling
description: software for BIM tooling

logo: https://github.com/C-Claus/Basic-BIM-Checker-for-Autodesk-Revit/blob/master/basic_bim_icons_dpi90/filter_level.png
show_downloads: "true"

